title: Pengfei.Xue
email: pengphy@gmail.com
description: ""
baseurl: "https://pengfei-xue.github.io/"
url: "https://pengfei-xue.github.com" # the base hostname & protocol for your site
twitter_username: pengphy
github_username:  pengfei-xue

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page/:num"
gems: [jekyll-paginate]
permalink: /:year/:month/:day/:title
highlighter: pygments
relative_permalinks: true
