title: Pengfei.Xue
email: pengphy@gmail.com
description: ""
baseurl: ""
url: "https://pengfei-xue.github.com"
twitter_username: pengphy
github_username:  pengfei-xue

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page/:num"
gems: [jekyll-paginate]
permalink: /:year/:month/:day/:title
highlighter: pygments
