title: Pengfei.Xue
email: pengphy@gmail.com
description: ""
baseurl: ""
url: "https://pengfei-xue.github.com"
twitter_username: pengphy
github_username:  pengfei-xue

# Build settings
# permalink   : /:year/:title/
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded
